tests: Adds missing includes.
With gcc11, 'test_service.cpp' and 'test_session.cpp' do not build anymore.

```
libqi/tests/messaging/test_service.cpp: In member function ‘virtual void QiService_RemoteObjectCacheServerClose_Test::TestBody()’:
libqi/tests/messaging/test_service.cpp:44:23: error: ‘sleep_for’ is not a member of ‘std::this_thread’
```

It seems the `<thread>` header was indirectly included before, but not with gcc11 standard library.
This patch therefore explicitly adds this include in these files.